api-version: '1.20'
name: NewPlayerPanel
version: 3.0.3
main: newplayerpanel.NewPlayerPanel
author: Math_Tereegor
description: Admin panel plugin for player management

commands:
  npp:
    description: NewPlayerPanel admin commands
    usage: |
      /npp reload - reload configuration
      /npp addrestriction <name> <type> <actions> [targets...] [time:N] [default:true/false]
    permission: newplayerpanel.admin
    permission-message: You don't have permission to use this command!
  history:
    description: View villager death history with search by player and coordinates
    usage: |
      /history - all records
      /history <player> - player records
      /history <x> <y> <z> - records by coordinates (±2 blocks)
      /history coords - records at your coordinates
      /history <player> <x> <y> <z> - combined search
      /history purge <time> - purge old records (7d, 30d, 1h...)
      /history summon <number> - summon villager from last viewed records
    permission: newplayerpanel.history
    permission-message: You don't have permission to use this command!
  restrict:
    description: Temporarily restrict a player
    usage: /restrict <player> <restriction> <time>
    permission: newplayerpanel.restrictions.restrict
    permission-message: You don't have permission to use this command!
  unrestrict:
    description: Remove restriction from a player
    usage: /unrestrict <player> <restriction|all>
    permission: newplayerpanel.restrictions.restrict
    permission-message: You don't have permission to use this command!
  restrictions:
    description: View active restrictions for a player
    usage: /restrictions [player]
    permission: newplayerpanel.restrictions.view
    permission-message: You don't have permission to use this command!

permissions:
  newplayerpanel.admin:
    description: Access to admin commands (reload, addrestriction)
    default: op
  newplayerpanel.history:
    description: Allows viewing villager death history
    default: op
  newplayerpanel.history.purge:
    description: Allows purging villager death history
    default: op
  newplayerpanel.history.summon:
    description: Allows summoning villagers from death history
    default: op
  newplayerpanel.notify:
    description: Receive notifications about traded villager deaths
    default: op
  newplayerpanel.restrictions.bypass:
    description: Bypass all restrictions from restrictions.yml
    default: op
  newplayerpanel.restrictions.restrict:
    description: Ability to apply temporary restrictions to players
    default: op
  newplayerpanel.restrictions.view:
    description: View your own active restrictions
    default: true
  newplayerpanel.restrictions.view.others:
    description: View other players' restrictions
    default: op
  newplayerpanel.spawnprotect.bypass:
    description: Bypass spawn protection restrictions
    default: op